### ISSUE TITLE
INSTALL_MODE

### ISSUE THREAD

**Issue by ghost** [otrego/go-type1#3]
The `installer.sh` script uses the `INSTALL_MODE` environment variable to set the mode, but then checks using the `MODE` variable.

When I first ran `./installer.sh install all`, I got three errors like:

    updmap [ERROR]: Either -sys or -user mode is required.
    updmap [ERROR]: In nearly all cases you should use updmap -sys.
    updmap [ERROR]: For special cases see https://tug.org/texlive/scripts-sys-user.html

When I replaced `if [[ $MODE == "user" ]]` with `if [[ $INSTALL_MODE == "user" ]]` (and also in the `elif`), there were no more errors.

**Comment by artasparks** [comment]
Oops, thanks! I'll send a fix.

**Comment by artasparks** [comment]
Ok, hopefully this is fixed now with https://github.com/otrego/go-type1/commit/75c8cecc878df4d31f2cd8d21527bf96aa29bcea
